<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <RootNamespace>simpleline.unit</RootNamespace>
        <AssemblyName>SimpleLine.Unit</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.2"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1"/>
        <PackageReference Include="NUnit" Version="4.2.2"/>
        <PackageReference Include="NUnit.Analyzers" Version="4.3.0"/>
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="src\extensions\" />
      <Folder Include="src\services\executor\help\helper\" />
      <Folder Include="src\services\executor\main\binder\actionOptions\arguments\" />
      <Folder Include="src\services\executor\main\binder\actionOptions\flags\" />
      <Folder Include="src\services\executor\main\binder\actionOptions\parameters\" />
      <Folder Include="src\services\executor\main\binder\commandOptions\arguments\" />
      <Folder Include="src\services\executor\main\binder\commandOptions\flags\" />
      <Folder Include="src\services\executor\main\binder\commandOptions\parameters\" />
      <Folder Include="src\services\executor\main\invoker\" />
      <Folder Include="src\services\executor\main\typizer\" />
      <Folder Include="src\services\registrar\" />
      <Folder Include="src\workers\parser\" />
      <Folder Include="src\workers\tokenizer\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SimpleLine\SimpleLine.csproj" />
    </ItemGroup>

</Project>
