### YamlMime:ManagedReference
items:
- uid: SimpleLineLibrary.Setup.Configuration
  commentId: T:SimpleLineLibrary.Setup.Configuration
  id: Configuration
  parent: SimpleLineLibrary.Setup
  children:
  - SimpleLineLibrary.Setup.Configuration.CommandNotFound
  - SimpleLineLibrary.Setup.Configuration.ExceptionHandler
  - SimpleLineLibrary.Setup.Configuration.HandlerNotFound
  - SimpleLineLibrary.Setup.Configuration.NoneArgsHandler
  langs:
  - csharp
  - vb
  name: Configuration
  nameWithType: Configuration
  fullName: SimpleLineLibrary.Setup.Configuration
  type: Class
  source:
    remote:
      path: SimpleLine/Setup/Configuration.cs
      branch: Rewrite
      repo: https://github.com/DrSa1fer/SimpleLine.git
    id: Configuration
    path: ../SimpleLine/Setup/Configuration.cs
    startLine: 2
  assemblies:
  - SimpleLine
  namespace: SimpleLineLibrary.Setup
  syntax:
    content: public class Configuration
    content.vb: Public Class Configuration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: SimpleLineLibrary.Setup.Configuration.ExceptionHandler
  commentId: P:SimpleLineLibrary.Setup.Configuration.ExceptionHandler
  id: ExceptionHandler
  parent: SimpleLineLibrary.Setup.Configuration
  langs:
  - csharp
  - vb
  name: ExceptionHandler
  nameWithType: Configuration.ExceptionHandler
  fullName: SimpleLineLibrary.Setup.Configuration.ExceptionHandler
  type: Property
  source:
    remote:
      path: SimpleLine/Setup/Configuration.cs
      branch: Rewrite
      repo: https://github.com/DrSa1fer/SimpleLine.git
    id: ExceptionHandler
    path: ../SimpleLine/Setup/Configuration.cs
    startLine: 4
  assemblies:
  - SimpleLine
  namespace: SimpleLineLibrary.Setup
  syntax:
    content: public Action<Exception>? ExceptionHandler { get; init; }
    parameters: []
    return:
      type: System.Action{System.Exception}
    content.vb: Public Property ExceptionHandler As Action(Of Exception)
  overload: SimpleLineLibrary.Setup.Configuration.ExceptionHandler*
- uid: SimpleLineLibrary.Setup.Configuration.NoneArgsHandler
  commentId: P:SimpleLineLibrary.Setup.Configuration.NoneArgsHandler
  id: NoneArgsHandler
  parent: SimpleLineLibrary.Setup.Configuration
  langs:
  - csharp
  - vb
  name: NoneArgsHandler
  nameWithType: Configuration.NoneArgsHandler
  fullName: SimpleLineLibrary.Setup.Configuration.NoneArgsHandler
  type: Property
  source:
    remote:
      path: SimpleLine/Setup/Configuration.cs
      branch: Rewrite
      repo: https://github.com/DrSa1fer/SimpleLine.git
    id: NoneArgsHandler
    path: ../SimpleLine/Setup/Configuration.cs
    startLine: 11
  assemblies:
  - SimpleLine
  namespace: SimpleLineLibrary.Setup
  syntax:
    content: public Action? NoneArgsHandler { get; init; }
    parameters: []
    return:
      type: System.Action
    content.vb: Public Property NoneArgsHandler As Action
  overload: SimpleLineLibrary.Setup.Configuration.NoneArgsHandler*
- uid: SimpleLineLibrary.Setup.Configuration.CommandNotFound
  commentId: P:SimpleLineLibrary.Setup.Configuration.CommandNotFound
  id: CommandNotFound
  parent: SimpleLineLibrary.Setup.Configuration
  langs:
  - csharp
  - vb
  name: CommandNotFound
  nameWithType: Configuration.CommandNotFound
  fullName: SimpleLineLibrary.Setup.Configuration.CommandNotFound
  type: Property
  source:
    remote:
      path: SimpleLine/Setup/Configuration.cs
      branch: Rewrite
      repo: https://github.com/DrSa1fer/SimpleLine.git
    id: CommandNotFound
    path: ../SimpleLine/Setup/Configuration.cs
    startLine: 27
  assemblies:
  - SimpleLine
  namespace: SimpleLineLibrary.Setup
  syntax:
    content: public Action<string>? CommandNotFound { get; init; }
    parameters: []
    return:
      type: System.Action{System.String}
    content.vb: Public Property CommandNotFound As Action(Of String)
  overload: SimpleLineLibrary.Setup.Configuration.CommandNotFound*
- uid: SimpleLineLibrary.Setup.Configuration.HandlerNotFound
  commentId: P:SimpleLineLibrary.Setup.Configuration.HandlerNotFound
  id: HandlerNotFound
  parent: SimpleLineLibrary.Setup.Configuration
  langs:
  - csharp
  - vb
  name: HandlerNotFound
  nameWithType: Configuration.HandlerNotFound
  fullName: SimpleLineLibrary.Setup.Configuration.HandlerNotFound
  type: Property
  source:
    remote:
      path: SimpleLine/Setup/Configuration.cs
      branch: Rewrite
      repo: https://github.com/DrSa1fer/SimpleLine.git
    id: HandlerNotFound
    path: ../SimpleLine/Setup/Configuration.cs
    startLine: 33
  assemblies:
  - SimpleLine
  namespace: SimpleLineLibrary.Setup
  syntax:
    content: public Action<IList<string>>? HandlerNotFound { get; init; }
    parameters: []
    return:
      type: System.Action{System.Collections.Generic.IList{System.String}}
    content.vb: Public Property HandlerNotFound As Action(Of IList(Of String))
  overload: SimpleLineLibrary.Setup.Configuration.HandlerNotFound*
references:
- uid: SimpleLineLibrary.Setup
  commentId: N:SimpleLineLibrary.Setup
  href: SimpleLineLibrary.html
  name: SimpleLineLibrary.Setup
  nameWithType: SimpleLineLibrary.Setup
  fullName: SimpleLineLibrary.Setup
  spec.csharp:
  - uid: SimpleLineLibrary
    name: SimpleLineLibrary
    href: SimpleLineLibrary.html
  - name: .
  - uid: SimpleLineLibrary.Setup
    name: Setup
    href: SimpleLineLibrary.Setup.html
  spec.vb:
  - uid: SimpleLineLibrary
    name: SimpleLineLibrary
    href: SimpleLineLibrary.html
  - name: .
  - uid: SimpleLineLibrary.Setup
    name: Setup
    href: SimpleLineLibrary.Setup.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: SimpleLineLibrary.Setup.Configuration.ExceptionHandler*
  commentId: Overload:SimpleLineLibrary.Setup.Configuration.ExceptionHandler
  href: SimpleLineLibrary.Setup.Configuration.html#SimpleLineLibrary_Setup_Configuration_ExceptionHandler
  name: ExceptionHandler
  nameWithType: Configuration.ExceptionHandler
  fullName: SimpleLineLibrary.Setup.Configuration.ExceptionHandler
- uid: System.Action{System.Exception}
  commentId: T:System.Action{System.Exception}
  parent: System
  definition: System.Action`1
  href: https://learn.microsoft.com/dotnet/api/system.action-1
  name: Action<Exception>
  nameWithType: Action<Exception>
  fullName: System.Action<System.Exception>
  nameWithType.vb: Action(Of Exception)
  fullName.vb: System.Action(Of System.Exception)
  name.vb: Action(Of Exception)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - uid: System.Exception
    name: Exception
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.exception
  - name: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Exception
    name: Exception
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.exception
  - name: )
- uid: System.Action`1
  commentId: T:System.Action`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.action-1
  name: Action<T>
  nameWithType: Action<T>
  fullName: System.Action<T>
  nameWithType.vb: Action(Of T)
  fullName.vb: System.Action(Of T)
  name.vb: Action(Of T)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: SimpleLineLibrary.Setup.Configuration.NoneArgsHandler*
  commentId: Overload:SimpleLineLibrary.Setup.Configuration.NoneArgsHandler
  href: SimpleLineLibrary.Setup.Configuration.html#SimpleLineLibrary_Setup_Configuration_NoneArgsHandler
  name: NoneArgsHandler
  nameWithType: Configuration.NoneArgsHandler
  fullName: SimpleLineLibrary.Setup.Configuration.NoneArgsHandler
- uid: System.Action
  commentId: T:System.Action
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.action
  name: Action
  nameWithType: Action
  fullName: System.Action
- uid: SimpleLineLibrary.Setup.Configuration.CommandNotFound*
  commentId: Overload:SimpleLineLibrary.Setup.Configuration.CommandNotFound
  href: SimpleLineLibrary.Setup.Configuration.html#SimpleLineLibrary_Setup_Configuration_CommandNotFound
  name: CommandNotFound
  nameWithType: Configuration.CommandNotFound
  fullName: SimpleLineLibrary.Setup.Configuration.CommandNotFound
- uid: System.Action{System.String}
  commentId: T:System.Action{System.String}
  parent: System
  definition: System.Action`1
  href: https://learn.microsoft.com/dotnet/api/system.action-1
  name: Action<string>
  nameWithType: Action<string>
  fullName: System.Action<string>
  nameWithType.vb: Action(Of String)
  fullName.vb: System.Action(Of String)
  name.vb: Action(Of String)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: SimpleLineLibrary.Setup.Configuration.HandlerNotFound*
  commentId: Overload:SimpleLineLibrary.Setup.Configuration.HandlerNotFound
  href: SimpleLineLibrary.Setup.Configuration.html#SimpleLineLibrary_Setup_Configuration_HandlerNotFound
  name: HandlerNotFound
  nameWithType: Configuration.HandlerNotFound
  fullName: SimpleLineLibrary.Setup.Configuration.HandlerNotFound
- uid: System.Action{System.Collections.Generic.IList{System.String}}
  commentId: T:System.Action{System.Collections.Generic.IList{System.String}}
  parent: System
  definition: System.Action`1
  href: https://learn.microsoft.com/dotnet/api/system.action-1
  name: Action<IList<string>>
  nameWithType: Action<IList<string>>
  fullName: System.Action<System.Collections.Generic.IList<string>>
  nameWithType.vb: Action(Of IList(Of String))
  fullName.vb: System.Action(Of System.Collections.Generic.IList(Of String))
  name.vb: Action(Of IList(Of String))
  spec.csharp:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - uid: System.Collections.Generic.IList`1
    name: IList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ilist-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Collections.Generic.IList`1
    name: IList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ilist-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
  - name: )
