### YamlMime:ManagedReference
items:
- uid: SimpleLineLibrary.Settings
  commentId: N:SimpleLineLibrary.Settings
  id: SimpleLineLibrary.Settings
  children:
  - SimpleLineLibrary.Settings.Configuration
  langs:
  - csharp
  - vb
  name: SimpleLineLibrary.Settings
  nameWithType: SimpleLineLibrary.Settings
  fullName: SimpleLineLibrary.Settings
  type: Namespace
  assemblies:
  - SimpleLine
references:
- uid: SimpleLineLibrary.Settings.Configuration
  commentId: T:SimpleLineLibrary.Settings.Configuration
  parent: SimpleLineLibrary.Settings
  href: SimpleLineLibrary.Settings.Configuration.html
  name: Configuration
  nameWithType: Configuration
  fullName: SimpleLineLibrary.Settings.Configuration
- uid: SimpleLineLibrary.Settings
  commentId: N:SimpleLineLibrary.Settings
  href: SimpleLineLibrary.html
  name: SimpleLineLibrary.Settings
  nameWithType: SimpleLineLibrary.Settings
  fullName: SimpleLineLibrary.Settings
  spec.csharp:
  - uid: SimpleLineLibrary
    name: SimpleLineLibrary
    href: SimpleLineLibrary.html
  - name: .
  - uid: SimpleLineLibrary.Settings
    name: Settings
    href: SimpleLineLibrary.Settings.html
  spec.vb:
  - uid: SimpleLineLibrary
    name: SimpleLineLibrary
    href: SimpleLineLibrary.html
  - name: .
  - uid: SimpleLineLibrary.Settings
    name: Settings
    href: SimpleLineLibrary.Settings.html
